version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 backend.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres.hrlcxabwygwztmkeuhun:Zc126922211zc!@aws-0-us-east-2.pooler.supabase.com:6543/postgres

volumes:
  postgres_data: